/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAppointmentsRouteImport } from './routes/_shell/appointments'
import { Route as ShellBillingRouteImport } from './routes/_shell/billing'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellPatientsRouteImport } from './routes/_shell/patients'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAppointmentsRoute = ShellAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBillingRoute = ShellBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatientsRoute = ShellPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof ShellAppointmentsRoute
  '/billing': typeof ShellBillingRoute
  '/dashboard': typeof ShellDashboardRoute
  '/patients': typeof ShellPatientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof ShellAppointmentsRoute
  '/billing': typeof ShellBillingRoute
  '/dashboard': typeof ShellDashboardRoute
  '/patients': typeof ShellPatientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/appointments': typeof ShellAppointmentsRoute
  '/_shell/billing': typeof ShellBillingRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/patients': typeof ShellPatientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appointments' | '/billing' | '/dashboard' | '/patients'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appointments' | '/billing' | '/dashboard' | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/appointments'
    | '/_shell/billing'
    | '/_shell/dashboard'
    | '/_shell/patients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/appointments': {
      id: '/_shell/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof ShellAppointmentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/billing': {
      id: '/_shell/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ShellBillingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/patients': {
      id: '/_shell/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ShellPatientsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAppointmentsRoute: typeof ShellAppointmentsRoute
  ShellBillingRoute: typeof ShellBillingRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellPatientsRoute: typeof ShellPatientsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAppointmentsRoute: ShellAppointmentsRoute,
  ShellBillingRoute: ShellBillingRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellPatientsRoute: ShellPatientsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
